version: '3.7'

services:

  web-app:
    build:
      context: './src/WebApp'
      dockerfile: Dockerfile
    command: npm run dev
    container_name: web-app
    depends_on:
      - words-service
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - './src/WebApp:/usr/src/app'
      - '/usr/src/app/node_modules'

  words-service:
    build:
      context: './src/Services/Words'
      dockerfile: Dockerfile
    command: npm run dev
    container_name: words-service
    ports:
      - '3001:80'
    restart: unless-stopped
    volumes:
      - './src/Services/Words:/usr/src/app'
      - '/usr/src/app/node_modules'
